---
version: "2.4"

networks:
  jadice-server-network:
    driver: bridge

services:
  # ### DIRECTOR ###
  # ===============================================
  jadice-director:
    mem_limit: "4294967296"
    mem_reservation: 2147483648
    image:  "${JS_DOCKER_REGISTRY_JADICE}js-director:2021.0-pre.0.23.1"
    user: '538446:538446'
    networks:
      - jadice-server-network
    depends_on:
      mariadb-director:
        condition: service_healthy
    restart: always
    environment:
      JS_DIRECTOR_ACCESS_TOKEN: ${JS_DIRECTOR_ACCESS_TOKEN}
    volumes:
      - ${JS_DC_PATH}/director-config:/app/config
    ports:
      - "8080:8080"

  # ### RUNTIME DB ###
  # ===============================================
  mariadb-director:
    mem_limit: "2147483648"
    mem_reservation: "1073741824"
    image: "${JS_DOCKER_REGISTRY_PROXY}mariadb:10.7.3-focal"
    #user: '999:999'
    restart: always
    networks:
      - jadice-server-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 1s
      retries: 3
    environment:
      MYSQL_ROOT_PASSWORD: letmebe
      MYSQL_DATABASE: jadice_server_director
    volumes:
      - ${JS_DC_PATH}/mariadb-config:/etc/mysql/conf.d
      - ${JS_DC_PATH}/mariadb-data:/var/lib/mysql
    ports:
      - "3306:3306"

  # ### S3 Storage ###
  # ===============================================
  minio:
    mem_limit: "4294967296"
    mem_reservation: "2147483648"
    image: "${JS_DOCKER_REGISTRY_PROXY}minio/minio:RELEASE.2022-03-26T06-49-28Z"
    restart: always
    volumes:
      - ${JS_DC_PATH}/minio-data:/data
    ports:
      - "${MINIO_PORT}:${MINIO_PORT}"
      - "${MINIO_CONSOLE_PORT}:${MINIO_CONSOLE_PORT}"
    networks:
      - jadice-server-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      MINIO_ROOT_USER: "${MINIO_ACCESS_KEY}"
      MINIO_ROOT_PASSWORD: "${MINIO_SECRET_KEY}"
      MINIO_BROWSER: "on"
    command: "server --address 0.0.0.0:${MINIO_PORT} --console-address :${MINIO_CONSOLE_PORT} /data"

  minio-client:
    image: "${JS_DOCKER_REGISTRY_PROXY}minio/mc:RELEASE.2022-03-17T20-25-06Z"
    entrypoint: ["/bin/bash", "/config/initialize"]
    networks:
      - jadice-server-network
    depends_on:
      minio:
        condition: service_healthy
    environment:
      MINIO_ENDPOINT: "${MINIO_ENDPOINT}"
      MINIO_PORT: "${MINIO_PORT}"
      MINIO_ACCESS_KEY: "${MINIO_ACCESS_KEY}"
      MINIO_SECRET_KEY: "${MINIO_SECRET_KEY}"
      INIT_BUCKET_NAME: jadice-server-ocr-bucket
      MINIO_PROTOCOL: "${MINIO_PROTOCOL}"
    volumes:
      - ${JS_DC_PATH}/minio-config:/config

  ## WORKER ###
  # ==============================================
  jadice-server-cloud-worker-tessocr:
    mem_limit: "8589934592"
    mem_reservation: "4294967296"
    image: "${JS_DOCKER_REGISTRY_JADICE}js-worker-tessocr:2021.0-pre.0.10.1"
    networks:
      - jadice-server-network
    restart: always
    user: '538446:538446'
    environment:
      MINIO_ENDPOINT: "${MINIO_ENDPOINT}"
      MINIO_PORT: "${MINIO_PORT}"
      MINIO_ACCESS_KEY: "${MINIO_ACCESS_KEY}"
      MINIO_SECRET_KEY: "${MINIO_SECRET_KEY}"
      MINIO_PROTOCOL: "${MINIO_PROTOCOL}"
    volumes:
      - ${JS_DC_PATH}/worker-config:/app/config
    ports:
      - "7081:8080"

  # ### S3 Proxy ###
  # ==============================================
  s3-proxy:
    image: "${JS_DOCKER_REGISTRY_JADICE}js-s3-upload-proxy:2021.0-pre.0.6.1"
    networks:
      - jadice-server-network
    restart: always
    user: '538446:538446'
    environment:
      MINIO_ENDPOINT: "${MINIO_ENDPOINT}"
      MINIO_PORT: "${MINIO_PORT}"
      MINIO_ACCESS_KEY: "${MINIO_ACCESS_KEY}"
      MINIO_SECRET_KEY: "${MINIO_SECRET_KEY}"
      MINIO_PROTOCOL: "${MINIO_PROTOCOL}"
    volumes:
      - ${JS_DC_PATH}/worker-config:/config
    ports:
      - "7082:8080"
...
