---
server:
  port: 8080
jss:
  basic:
    access-token: ${JF_DIRECTOR_ACCESS_TOKEN}
  engine:
    paralleljobs:
      def: 4
  register:
    jobtypes:
      - type: "ocr"
        uri: "http://jadice-flow-worker-tessocr:8080"
        displayName: "Tesseract OCR"
        description: "This worker performs OCR analysis and can return text, PDF, and hOCR."
  db-clean-job:
    # Run the job every weekday at 4:05 AM.
    cronSchedule: "0 5 4 * * MON-FRI"
    databaseRetentionDays: 21
    # for debug: Run once every minute.
    #cronSchedule: "0 */1 * * * *"
spring:
  datasource:
    url: "jdbc:mariadb://mariadb-director/jadice_flow_director"
    username: root
    password: letmebe
    driver-class-name: org.mariadb.jdbc.Driver
  hikari:
    maxLifetime: 120000
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    open-in-view: true
  # do no try to run any jobs automatically at startup
  batch:
    job.enabled: false
jadice:
  monitoring:
    enabled: false
...
