jadice-flow.jobs:
  jobTemplates:
  - jobName: "ocr"
    description: "Performs optical character recognition for the given input image(s). Default output is one plain text part and one HOCR part."
    properties: {}
    enabled: true
    stepTemplates:
      - stepName: "OCR"
        workerDefinitionName: "TessOCR"
        inputMimeTypes:
          - "image/png"
          - "application/pdf"
          - "application/octet-stream"
          - "image/jpeg"
          - "image/tiff"
          - "image/bmp"
          - "image/gif"
        expectsNewPartResult: true
        markSrcAsMetaOnResult: true
        parameters:
          - name: "output-formats"
            type: "com.jadice.flow.worker.ocr.OCROutputSetting"
            subTypes: []
            value: "\"TEXT_AND_HOCR\""
            description: "OCR output format(s)"
    jobFlow:
      - from: ""
        "on": "*"
        to: "OCR"
