jadice-flow.workers:
  workerDefinitions:
  - workerName: "TessOCR"
    description: "Performs optical character recognition on the given image parts\
      \ and stores the result as new part"
    processorClass: "com.jadice.flow.controller.server.processor.impl.TessOCRProcessor"
    workerURL: "http://jadice-flow-worker-tessocr:8080/"
    infoTags:
    - "PART_BASED"
    - "IMAGE_PROCESSING"
    - "REMOTE"
    workerParameters:
    - name: "output-formats"
      type: "com.jadice.flow.worker.ocr.OCROutputSetting"
      subTypes: null
      value: "\"TEXT\""
      description: "OCR output format(s)"
