---
version: "2.4"

networks:
  jadice-flow-network:
    driver: bridge

services:
  # ### DIRECTOR ###
  # ===============================================
  jadice-director:
    mem_limit: "4294967296"
    mem_reservation: 2147483648
    image:  "${JF_CONTAINER_REGISTRY_JADICE}jf-director:0.24.1"
    user: '538446:538446'
    networks:
      - jadice-flow-network
    depends_on:
      - mariadb-director
        # condition: service_healthy
    restart: always
    environment:
      JF_DIRECTOR_ACCESS_TOKEN: ${JF_DIRECTOR_ACCESS_TOKEN}
    volumes:
      - ./director-config:/app/config
    ports:
      - "8080:8080"

  # ### RUNTIME DB ###
  # ===============================================
  mariadb-director:
    mem_limit: "2147483648"
    mem_reservation: "1073741824"
    image: "${JF_CONTAINER_REGISTRY_PROXY}mariadb:10.7.3-focal"
    #user: '999:999'
    restart: always
    networks:
      - jadice-flow-network
    # healthcheck:
      # test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      # interval: 10s
      # timeout: 1s
      # retries: 3
    environment:
      MYSQL_ROOT_PASSWORD: letmebe
      MYSQL_DATABASE: jadice_flow_director
    volumes:
      - ./mariadb-config:/etc/mysql/conf.d:ro
      - ./mariadb-data:/var/lib/mysql
    ports:
      - "3306:3306"

  # ### S3 Storage ###
  # ===============================================
  minio:
    mem_limit: "4294967296"
    mem_reservation: "2147483648"
    image: "${JF_CONTAINER_REGISTRY_PROXY}minio/minio:RELEASE.2022-05-04T07-45-27Z"
    restart: always
    volumes:
      - ./minio-data:/data
    ports:
      - "${MINIO_PORT}:${MINIO_PORT}"
      - "${MINIO_CONSOLE_PORT}:${MINIO_CONSOLE_PORT}"
    networks:
      - jadice-flow-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      MINIO_ROOT_USER: "${MINIO_ACCESS_KEY}"
      MINIO_ROOT_PASSWORD: "${MINIO_SECRET_KEY}"
      MINIO_BROWSER: "on"
    command: "server --address 0.0.0.0:${MINIO_PORT} --console-address :${MINIO_CONSOLE_PORT} /data"

  minio-client:
    image: "${JF_CONTAINER_REGISTRY_PROXY}minio/mc:RELEASE.2022-05-04T06-07-55Z"
    entrypoint: ["/bin/bash", "/config/initialize"]
    networks:
      - jadice-flow-network
    depends_on:
      minio:
        condition: service_healthy
    environment:
      MINIO_ENDPOINT: "${MINIO_ENDPOINT}"
      MINIO_PORT: "${MINIO_PORT}"
      MINIO_ACCESS_KEY: "${MINIO_ACCESS_KEY}"
      MINIO_SECRET_KEY: "${MINIO_SECRET_KEY}"
      INIT_BUCKET_NAME: jadice-flow-ocr-bucket
      MINIO_PROTOCOL: "${MINIO_PROTOCOL}"
    volumes:
      - C:\Users\wirlls\jadice-flow-getting-started\jadice-flow-tutorial-01\docker-compose\local-ocr\minio-config:/config

  ## WORKER ###
  # ==============================================
  jadice-flow-worker-tessocr:
    mem_limit: "8589934592"
    mem_reservation: "4294967296"
    image: "${JF_CONTAINER_REGISTRY_JADICE}jf-worker-tessocr:1.1.0"
    networks:
      - jadice-flow-network
    restart: always
    user: '538446:538446'
    environment:
      MINIO_ENDPOINT: "${MINIO_ENDPOINT}"
      MINIO_PORT: "${MINIO_PORT}"
      MINIO_ACCESS_KEY: "${MINIO_ACCESS_KEY}"
      MINIO_SECRET_KEY: "${MINIO_SECRET_KEY}"
      MINIO_PROTOCOL: "${MINIO_PROTOCOL}"
    volumes:
      - ./worker-config:/app/config
    ports:
      - "7081:8080"

  # ### S3 Proxy ###
  # ==============================================
  s3-proxy:
    image: "${JF_CONTAINER_REGISTRY_JADICE}jf-s3-proxy:0.9.1"
    networks:
      - jadice-flow-network
    restart: always
    user: '538446:538446'
    environment:
      MINIO_ENDPOINT: "${MINIO_ENDPOINT}"
      MINIO_PORT: "${MINIO_PORT}"
      MINIO_ACCESS_KEY: "${MINIO_ACCESS_KEY}"
      MINIO_SECRET_KEY: "${MINIO_SECRET_KEY}"
      MINIO_PROTOCOL: "${MINIO_PROTOCOL}"
    volumes:
      - ./worker-config:/config
    ports:
      - "7082:8080"
...
