---
version: "2.4"

networks:
  jadice-flow-network:
    driver: bridge

services:

  jf-controller:
    mem_limit: "4294967296"
    mem_reservation: 2147483648
    image:  "${JF_CONTAINER_REGISTRY_JADICE}jadice-flow-controller:0.26.5"
    user: '538446:538446'
    networks:
      - jadice-flow-network
    restart: always
    environment:
      JF_ACCESS_TOKEN: ${JF_ACCESS_TOKEN}
      EUREKA_ENDPOINT: http://eureka:8080
      EUREKA_USERNAME: "${EUREKA_USERNAME}"
      EUREKA_PASSWORD: "${EUREKA_PASSWORD}"
    volumes:
      - ./controller-config:/app/config
    ports:
      - "8080:8080"

  jadice-flow-worker-tessocr:
    mem_limit: "8589934592"
    mem_reservation: "4294967296"
    image: "${JF_CONTAINER_REGISTRY_JADICE}jf-worker-tessocr:1.8.0"
    networks:
      - jadice-flow-network
    restart: always
    user: '538446:538446'
    environment:
      EUREKA_ENDPOINT: http://eureka:8080
      EUREKA_USERNAME: "${EUREKA_USERNAME}"
      EUREKA_PASSWORD: "${EUREKA_PASSWORD}"
    volumes:
      - ./worker-config:/app/config
    ports:
      - "7081:8080"

  eureka:
    mem_limit: "4294967296"
    mem_reservation: "2147483648"
    image: "${JF_CONTAINER_REGISTRY_JADICE}neverpile-eureka-boxed:0.2.7"
    restart: always
    volumes:
      - ./eureka-config:/config
      - ./eureka-data:/data/neverpile-eureka_default
    environment:
      EUREKA_USERNAME: "${EUREKA_USERNAME}"
      EUREKA_PASSWORD: "${EUREKA_PASSWORD}"
    ports:
      - "8085:8080"
    networks:
      - jadice-flow-network
...
