---
stage: dev

publisher:
  eureka:
    endpoint: "${EUREKA_ENDPOINT}"
    username: "${EUREKA_USERNAME}"
    password: "${EUREKA_PASSWORD}"

spring:
  application:
    name: jadice-flow-worker-ocr

opentracing:
  jaeger:
    log-spans: false
    service-name: ${spring.application.name}
    tags:
      stage: ${stage}

management:
  endpoint.health.enabled: true
  endpoint.prometheus.enabled: true
  endpoint.info.enabled: true
  endpoints:
    # set endpoint enablement to be opt-in
    enabled-by-default: false
    web:
      exposure:
        include: "health,prometheus,info"
  metrics:
    enable:
      all: true
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
...
