---
stage: dev
publisher:
  s3:
    bucket: jadice-flow-ocr-bucket
    endpoint: "${MINIO_PROTOCOL}://${MINIO_ENDPOINT}:${MINIO_PORT}"
    access-key: "${MINIO_ACCESS_KEY}"
    secret-key: "${MINIO_SECRET_KEY}"
    protocol: "${MINIO_PROTOCOL}"

spring:
  application:
    name: jadice-flow-worker-ocr

opentracing:
  jaeger:
    log-spans: true
    service-name: ${spring.application.name}
    tags:
      stage: ${stage}

management:
  endpoint.health.enabled: true
  endpoint.prometheus.enabled: true
  endpoint.info.enabled: true
  endpoints:
    # set endpoint enablement to be opt-in
    enabled-by-default: false
    web:
      exposure:
        include: "health,prometheus,info"
  metrics:
    enable:
      all: true
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
...
